import { useEffect, useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, Check, Code2, Database, Github, Globe2, Layers3, Linkedin, Menu, Moon, Sun, X } from 'lucide-react';
import { experience, skillGroups } from '../data/profile';
import { withBasePath } from '../utils/assetPath';
import ProjectGallery from './ProjectGallery';
import Mentorship from './Mentorship';
import SpatialMotion from './SpatialMotion';
import '../portfolio.css';

const navigation = ['About', 'Work', 'Projects', 'Experience', 'Skills', 'Mentorship', 'Education'];
const icons = [Layers3, Code2, Globe2, Database];

export default function PortfolioPage() {
 const [dark, setDark] = useState(() => {
   try { const saved = localStorage.getItem('theme'); if (saved === 'dark' || saved === 'light') return saved === 'dark'; } catch { /* Storage is optional. */ }
   return window.matchMedia('(prefers-color-scheme: dark)').matches;
 });
 const [menuOpen, setMenuOpen] = useState(false);
 useEffect(() => { document.documentElement.classList.toggle('dark', dark); try { localStorage.setItem('theme', dark ? 'dark' : 'light'); } catch { /* Theme works without persistence. */ } }, [dark]);
 useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === 'Escape') setMenuOpen(false); }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, []);
 return <>
  <SpatialMotion />
  <a className="skip-link" href="#main">Skip to content</a>
  <header className="site-header"><div className="shell header-inner">
   <a href="#home" className="wordmark" aria-label="Reza, home">reza<span>.</span><small>ENGINEER & BUILDER</small></a>
   <nav id="main-navigation" className={menuOpen ? 'navigation open' : 'navigation'} aria-label="Main navigation">{navigation.map(label => <a key={label} href={`#${label === 'Projects' ? 'portfolio' : label.toLowerCase()}`} onClick={() => setMenuOpen(false)}>{label}</a>)}<a href="#contact" onClick={() => setMenuOpen(false)}>Let’s talk ↗</a></nav>
   <div className="header-actions"><button className="icon-button" aria-label={`Switch to ${dark ? 'light' : 'dark'} mode`} onClick={() => setDark(!dark)}>{dark ? <Sun size={19} /> : <Moon size={19} />}</button><button className="icon-button menu-toggle" aria-label={menuOpen ? 'Close navigation' : 'Open navigation'} aria-expanded={menuOpen} aria-controls="main-navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={21} /> : <Menu size={21} />}</button></div>
  </div></header>
  <main id="main">
   <section id="home" className="hero shell"><div className="hero-copy">
    <div className="availability"><span /> Immediately available for opportunities</div>
    <p className="eyebrow hero-intro">RIZVE RAHMAN REZA · DHAKA, BANGLADESH</p>
    <h1>Enterprise logic.<br />Human experience.<br /><em>Connected.</em></h1>
    <p className="hero-position">SAP B1 + .NET Integration Specialist</p>
    <p className="hero-description">I connect enterprise ERP with modern web applications — bringing SAP Business One, .NET, and Angular together to solve real business problems.</p>
    <div className="actions"><a className="button primary" href="#work">Explore my work <ArrowDown size={17} /></a><a className="text-link" href="mailto:rizverahman.ai@gmail.com">Let’s build together <ArrowUpRight size={17} /></a></div>
    <a className="text-link resume-link" href={withBasePath('cv/Rizve_Rahman_Reza_CV.pdf')} download>Download résumé <ArrowDown size={15} /></a>
    <div className="hero-footnote"><span>SAP Business One Developer</span><span>Full-Stack .NET Developer</span></div>
   </div><div className="hero-visual"><div className="portrait-frame"><img src={withBasePath('about.jpg')} alt="Rizve Rahman Reza" width="640" height="760" loading="eager" /><div className="portrait-caption"><span>THE PERSON BEHIND THE CODE</span><strong>Hi, I’m Reza.<ArrowUpRight size={23} /></strong></div></div><div className="stack-note"><span className="status-dot" />FROM ERP TO THE WEB<div><span>SAP B1</span><ArrowRight size={15} /><span>.NET</span><ArrowRight size={15} /><span>Angular</span></div></div></div></section>
   <div className="impact-strip"><div className="shell impact-grid"><div><strong>Up to 80<span>%</span></strong><p>Application performance improvement<small>Database & caching optimization · SAP B1/HANA + .NET</small></p></div><div><strong>30<span>+</span></strong><p>Developers mentored<small>.NET training & coding best practices</small></p></div><div><strong>End to end</strong><p>From enterprise systems to production<small>ERP customization · APIs · customer experiences</small></p></div></div></div>
   <section id="about" className="shell section about-grid"><div><p className="eyebrow">01 / ABOUT</p><h2>Two worlds.<br />One engineer.</h2></div><div className="about-copy"><p className="lead">I work where business operations meet software — turning complex requirements into tools people can depend on.</p><p>I’m Rizve Rahman Reza, a SAP Business One developer and full-stack engineer based in Dhaka, Bangladesh. My experience spans SAP B1/HANA customization, ASP.NET Core, and Angular, combining enterprise ERP development with modern application engineering.</p><p>From SAP B1 SDK integrations, Crystal Reports, and HANA stored procedures to production e-commerce, I care about reliable workflows, fast data access, and a clear user experience.</p><a className="text-link" href="#experience">Explore my experience <ArrowRight size={17} /></a></div></section>
   <section id="work" className="section work-section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">02 / FEATURED WORK</p><h2>Built. Shipped. In use.</h2></div><span className="small-note">A closer look at production engineering.</span></div>
    <article className="case-study"><div className="case-banner"><div><span className="live-label"><span /> LIVE IN PRODUCTION</span><h3>Arza Mart<span>Commerce, from first click<br />to completed order.</span></h3><p>An e-commerce platform built and shipped end to end, serving live customer traffic on IIS / Windows shared hosting.</p><div className="tags">{['Angular 18', 'ASP.NET Core 8', 'Tailwind CSS', 'IIS', 'SQL Server'].map(tag => <span key={tag}>{tag}</span>)}</div></div><div className="system-map" aria-label="Arza Mart architecture: Angular storefront, ASP.NET Core, AppCache, SQL Server and attribution tracking"><p>UNDER THE HOOD <Code2 size={17} /></p><div className="system-node">Angular storefront <Globe2 size={20} /></div><span className="connector">↓</span><div className="system-node api-node">ASP.NET Core 8 <Code2 size={20} /></div><span className="connector">↓</span><div className="system-pair"><div>AppCache<small>Singleton cache</small></div><div>SQL Server<small>Persistent data</small></div></div><div className="tracking-note"><Check size={15} /> Lead & order tracking · UTM / fbclid</div></div></div>
    <div className="case-details"><div><span className="detail-number">01 / THE CHALLENGE</span><h4>A complete production platform.</h4><p>Deliver the storefront and backend together, manage conflicting caching mechanisms, and make abandoned leads and incomplete orders visible.</p></div><div><span className="detail-number">02 / THE ENGINEERING</span><h4>One consistent caching layer.</h4><p>Designed AppCache around a Singleton ConcurrentDictionary, replacing multiple conflicting caching mechanisms. Built abandoned-lead and incomplete-order tracking with UTM and fbclid attribution.</p></div><div><span className="detail-number">03 / THE OUTCOME</span><h4>Live traffic. Useful insight.</h4><p>Shipped to IIS / Windows shared hosting with live customer traffic and attribution tracking to support Facebook ad analysis.</p></div></div></article><a className="text-link work-github" href="https://github.com/RezaRahmanAI" target="_blank" rel="noreferrer">Explore my GitHub <ArrowUpRight size={17} /></a>
   </div></section>
   <ProjectGallery />
   <section id="experience" className="shell section experience-grid"><div className="experience-heading"><p className="eyebrow">03 / EXPERIENCE</p><h2>Building skills.<br />Delivering impact.</h2><p>Enterprise systems, full-stack development, and sharing what I learn.</p></div><ol className="timeline">{experience.map((job, index) => <li key={job.role}><div className={`timeline-dot ${index === 0 ? 'latest' : ''}`} /><p className="job-period">{job.period}<span>Dhaka, Bangladesh</span></p><h3>{job.role}</h3><p className="company">{job.company}</p><ul>{job.points.map(point => <li key={point}>{point}</li>)}</ul></li>)}</ol></section>
   <section id="skills" className="section skills-section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">04 / TOOLKIT</p><h2>The right tools.<br />Across the whole stack.</h2></div><p className="small-note">From business data to the interface.<br />A connected set of capabilities.</p></div><div className="skills-grid">{skillGroups.map((group, index) => { const Icon = icons[index]; return <article className="skill-group" key={group.name}><Icon size={25} strokeWidth={1.5} /><span className="skill-number">0{index + 1}</span><h3>{group.name}</h3><p>{group.description}</p><ul>{group.skills.map(skill => <li key={skill}>{skill}</li>)}</ul></article>; })}</div><div className="principles"><span>ENGINEERING FOUNDATIONS</span><p>Data Structures & Algorithms <b>·</b> SOLID <b>·</b> CQRS</p></div></div></section>
   <Mentorship />
   <section id="education" className="shell section education-grid"><div><p className="eyebrow">05 / EDUCATION</p><h2>A foundation<br />to build on.</h2></div><div className="education-list"><article><span>2020 — 2023</span><h3>B.Sc in CSE</h3><p>Green University of Bangladesh</p></article><article><span>2015 — 2019</span><h3>Diploma in CSE</h3><p>Magura Polytechnic Institute</p></article><article><span>CERTIFICATION · UDEMY · 40 HRS</span><h3>Full-Stack Development with ASP.NET Core and Angular</h3></article></div></section>
   <section id="contact" className="contact-section"><div className="shell"><div className="availability"><span /> Immediately available</div><h2>Have a challenge?<br /><em>Let’s connect the dots.</em></h2><p>Open to full-time, contract, and remote opportunities.<br />Based in Dhaka. Ready to work with teams worldwide.</p><a className="contact-email" href="mailto:rizverahman.ai@gmail.com">rizverahman.ai@gmail.com <ArrowUpRight /></a><div className="contact-links"><a href="tel:+8801316928662">+880 1316 928662</a><a href="https://github.com/RezaRahmanAI" target="_blank" rel="noreferrer"><Github size={17} /> GitHub ↗</a><a href="https://www.linkedin.com/in/rizve-rahman-reza/" target="_blank" rel="noreferrer"><Linkedin size={17} /> LinkedIn ↗</a></div></div></section>
  </main><footer className="shell site-footer"><a href="#home" className="wordmark">reza<span>.</span></a><p>© {new Date().getFullYear()} Rizve Rahman Reza</p><a href="#home" className="text-link">Back to top ↑</a></footer>
 </>;
}
